### ISSUE TITLE
Feature Request: Hide Controls

### ISSUE THREAD

**Issue by RacerDelux** [nkoehler/mat-video#11]
It would be very useful if there was an option to hide the controls. On the standard HTML video tag, just not including the controls attribute would remove them.

**Comment by nkoehler** [comment]
Version 2.6.0 has been released which allows you to force the state of the overlay/controls, instead of using the default behaviour.

You can disable the overlay/controls as follows.  You can bind this to a boolean variable to dynamically alter the behaviour.

```html
<mat-video src="/assets/video.mp4" [overlay]="false">
```
Options:

- [overlay]="null" - default behaviour
- [overlay]="false" - always hide the overlay
- [overlay]="true" - always show the overlay

Not including the overlay attribute falls back on the default behaviour.

The documentation and sample have both been updated to reflect this change.

Closing.
